# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

run-name: Github Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test --if-present
      - run: npm run coverage --if-present

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy latest commit to Render
        env:
          RENDER_WEBHOOK: ${{ secrets.RENDER_WEBHOOK }}
        run: |
          curl -X POST -d $RENDER_WEBHOOK \
          -H "Content-Type: application/json" \
          -d '{"event": "deploy this code"}'
